# Generated by Django 6.1.1 on 2026-09-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kitap adı')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Yazar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme tarihi')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Wattpad bölüm linki', unique=True, verbose_name='Wattpad linki')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Bölüm başlığı')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('content', models.TextField(blank=True, help_text='Çekilmiş bölüm metni', verbose_name='Metin')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Çekilme zamanı')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reader.book', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
                'ordering': ['order', 'id'],
            },
        ),
    ]
